In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
from IPython.core.debugger import Pdb
import torch
import torch.nn as nn
import torch.nn.functional as F

In [37]:
a = torch.arange(10000)
a = a.view(100, -1)
a

tensor([[   0,    1,    2,  ...,   97,   98,   99],
        [ 100,  101,  102,  ...,  197,  198,  199],
        [ 200,  201,  202,  ...,  297,  298,  299],
        ...,
        [9700, 9701, 9702,  ..., 9797, 9798, 9799],
        [9800, 9801, 9802,  ..., 9897, 9898, 9899],
        [9900, 9901, 9902,  ..., 9997, 9998, 9999]])

In [38]:
def split(t=1_000_000):
    for i in range(t):
        a_ = torch.split(a, 50, dim=1)
    return a_

In [39]:
def split2(t=1_000_000):
    for i in range(t):
        a_ = (a[:, :50], a[:, 51:])
    return a_

In [44]:
%%time
split(10000)

CPU times: user 48.2 ms, sys: 2.62 ms, total: 50.9 ms
Wall time: 53.4 ms


(tensor([[   0,    1,    2,  ...,   47,   48,   49],
         [ 100,  101,  102,  ...,  147,  148,  149],
         [ 200,  201,  202,  ...,  247,  248,  249],
         ...,
         [9700, 9701, 9702,  ..., 9747, 9748, 9749],
         [9800, 9801, 9802,  ..., 9847, 9848, 9849],
         [9900, 9901, 9902,  ..., 9947, 9948, 9949]]),
 tensor([[  50,   51,   52,  ...,   97,   98,   99],
         [ 150,  151,  152,  ...,  197,  198,  199],
         [ 250,  251,  252,  ...,  297,  298,  299],
         ...,
         [9750, 9751, 9752,  ..., 9797, 9798, 9799],
         [9850, 9851, 9852,  ..., 9897, 9898, 9899],
         [9950, 9951, 9952,  ..., 9997, 9998, 9999]]))

In [45]:
%%time
split2(10000)

CPU times: user 66.6 ms, sys: 2.44 ms, total: 69 ms
Wall time: 71.4 ms


(tensor([[   0,    1,    2,  ...,   47,   48,   49],
         [ 100,  101,  102,  ...,  147,  148,  149],
         [ 200,  201,  202,  ...,  247,  248,  249],
         ...,
         [9700, 9701, 9702,  ..., 9747, 9748, 9749],
         [9800, 9801, 9802,  ..., 9847, 9848, 9849],
         [9900, 9901, 9902,  ..., 9947, 9948, 9949]]),
 tensor([[  51,   52,   53,  ...,   97,   98,   99],
         [ 151,  152,  153,  ...,  197,  198,  199],
         [ 251,  252,  253,  ...,  297,  298,  299],
         ...,
         [9751, 9752, 9753,  ..., 9797, 9798, 9799],
         [9851, 9852, 9853,  ..., 9897, 9898, 9899],
         [9951, 9952, 9953,  ..., 9997, 9998, 9999]]))